### PR TITLE
Initially create wmde.10 (1.38)

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Comment by addshore** [comment]
So it looks like the client tests around dispatching are not working (behaviour has changed in this release)
https://github.com/wmde/wikibase-release-pipeline/actions/runs/3446873839/jobs/5752544609

And also 1 in repo

```
[Chrome Headless 93.0.4577.82 linux #0-1] Running: Chrome Headless (v93.0.4577.82) on linux
[Chrome Headless 93.0.4577.82 linux #0-1] Session ID: 716ccd8d-6a36-483c-81e3-815a80e29aa6
[Chrome Headless 93.0.4577.82 linux #0-1]
[Chrome Headless 93.0.4577.82 linux #0-1] » /specs/repo/property.js
[Chrome Headless 93.0.4577.82 linux #0-1] Property
[Chrome Headless 93.0.4577.82 linux #0-1]    ✖ Should be able to add statement and reference to property
[Chrome Headless 93.0.4577.82 linux #0-1]    ✖ Should contain statement and reference in EntityData
[Chrome Headless 93.0.4577.82 linux #0-1]
[Chrome Headless 93.0.4577.82 linux #0-1] 2 failing (39.6s)
[Chrome Headless 93.0.4577.82 linux #0-1]
[Chrome Headless 93.0.4577.82 linux #0-1] 1) Property Should be able to add statement and reference to property
[Chrome Headless 93.0.4577.82 linux #0-1] element ("=P101 (P101)") still not displayed after 30000ms
[Chrome Headless 93.0.4577.82 linux #0-1] Error: element ("=P101 (P101)") still not displayed after 30000ms
[Chrome Headless 93.0.4577.82 linux #0-1]     at Element.<anonymous> (/usr/src/app/node_modules/@wdio/utils/build/shim.js:239:24)
[Chrome Headless 93.0.4577.82 linux #0-1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[Chrome Headless 93.0.4577.82 linux #0-1]     at Context.<anonymous> (/usr/src/app/specs/repo/property.js:38:27)
[Chrome Headless 93.0.4577.82 linux #0-1]
[Chrome Headless 93.0.4577.82 linux #0-1] 2) Property Should contain statement and reference in EntityData
[Chrome Headless 93.0.4577.82 linux #0-1] Cannot read property '0' of undefined
[Chrome Headless 93.0.4577.82 linux #0-1] TypeError: Cannot read property '0' of undefined
[Chrome Headless 93.0.4577.82 linux #0-1]     at Context.<anonymous> (/usr/src/app/specs/repo/property.js:52:37)
```

**Comment by addshore** [comment]
So, the TODO list for this PR now is:
 - [ ] Write some fresh federated properties tests
 - [ ] Include the fix for https://phabricator.wikimedia.org/T326082 and re-enable tests
 - [ ] Update everything 1 more time for January
 
 Then this PR should be green and ready to continue with the rest of the checklist at https://phabricator.wikimedia.org/T322407

**Comment by addshore** [comment]
It was decided a fix for https://phabricator.wikimedia.org/T326082 is not needed in this release, so i can push forward

**Comment by addshore** [comment]
Initial tests on the testr system look good, so this is probabl ready to merge

**Review by manicki — APPROVED** [review]
Looks good. I would have skipped the tests instead of deleting them but it is minor preference detail.
Will submit a follow up putting final details into CHANGES.md file

**Pull request merged**
