### PR TITLE
T296812: add faq item about volume storage location

### PR DESCRIPTION
**Pull request by rti**
https://phabricator.wikimedia.org/T296812

### CODE REVIEW

**Review by lorenjohnson — COMMENTED** [review]
I'm thinking this would be better as a more brief summary and a link/s to the related Docker documentation.  My biggest concern here is the scope of what we maintain in our docs, which we need to discuss and decide on as a team.

**Review by darthmon — APPROVED** [review]
It looks good to me!

I see Loren's point of view but I also think that how the text has been cooked is personalised enough for our users and this is what matters most as I see it. 

However, it is true that we could also add a link to the docker docs for users who want to go look for further information.

**Comment by datn** [comment]
Sorry for my lateness, I was out sick part of last week. I agree with @lorenjohnson -- this is out of scope for our work. I recommend a single helpful link to the relevant portion of the Docker docs as a courtesy.

**Review by datn — CHANGES_REQUESTED** [review]
See my comment in the PR -- I think this is out of scope for our docs and should be replaced with a helpful link to the Docker docs.

**Pull request closed without merging**
