### PR TITLE
feat!: set wdqs concept URI

### PR DESCRIPTION
**Pull request by rti**
Allow setting the concept URI of entities in WDQS explicitly and distinct from the hostname used to contact wikibase.

This also fixes the problem WDQS not accepting entities when the wikibase host had a DNS name different from `wikibase` (which should be always the case, because `wikibase` is not a FQDN).

**Note: In deploy, items and properties in WDQS will now have the public wikibase hostname with https protocol as prefix. E.g. https://wikibase.example/**

Related:
- https://phabricator.wikimedia.org/T376016
- https://github.com/wmde/wikibase-release-pipeline/issues/385
- https://phabricator.wikimedia.org/T197682
- https://phabricator.wikimedia.org/T376106

BREAKING CHANGE: env var WIKIBASE_CONCEPT_URI now mandatory to run wdqs updater

### CODE REVIEW

**Comment by rti** [comment]
related https://phabricator.wikimedia.org/T197682

**Review by lorenjohnson — COMMENTED** [review]
This looks like it should go forward, and would be nice to backport. However, given the major versioning to 1.x and 2.x issue we've been talking about I wonder if there is any sensible way to maintain the current way it functions (even if not optimal or broken) so that it can be a minor release? 🤷🏼‍♂️

**Comment by rti** [comment]
How to handle this versioning, as discussed today with @lorenjohnson 

### WDQS bumps a major version
- because the interface changes the API in a breaking way
- it has a new required environment variable

### Deploy bumps a patch
- deploy bumps to WDQS 2 under the hood
- provides the required variable to WDQS
- for the user, the interface / API of deploy does not change

### TODO
- clean up commit messages to signify correct version bumps to deploy and WDQS projects
- do not squash merge, use merge commits

**Comment by rti** [comment]
holding back for #782

**Review by lorenjohnson — APPROVED** [review]
LGTM!

**Pull request merged**
