### PR TITLE
Backporting for releaseprep 1.39.7

### PR DESCRIPTION
**Pull request by adeeri**

### CODE REVIEW

**Comment by RickiJay-WMDE** [comment]
I think you'll need to branch `releaseprep-wmde.18` off of `mw-1.39`, then merge this into `releaseprep-wmde.18` instead of `main`, then finish `releaseprep-wmde.18`

**Comment by rti** [comment]
For the final release we will need #642 here as well, as done in #646

https://phabricator.wikimedia.org/T362394

**Comment by adeeri** [comment]
> I think the base branch needs to be updated on this PR...

Correct! Thanks

**Comment by adeeri** [comment]
> I think you'll need to branch `releaseprep-wmde.18` off of `mw-1.39`, then merge this into `releaseprep-wmde.18` instead of `main`, then finish `releaseprep-wmde.18`

Yes, that was the plan, thanks

**Pull request closed without merging**
