### PR TITLE
Bump WDQS to 0.3.97 for wmde.4

### PR DESCRIPTION
**Pull request by toban**
this PR is based on `add-wdqs-to-upgrade-test` which would like to get merged first.

### CODE REVIEW

**Comment by toban** [comment]
We could also just remove the streaming-updater-producer when we build here, might be the better solution.

**Comment by manicki** [comment]
> We could also just remove the streaming-updater-producer when we build here, might be the better solution.

I didn't fully get this comment. Do you mean the the new version of "WDQS" includes the service ("streaming-updater-producer") packed in, that Wikibase users wouldn't use (for now)? And suggest to remove it from the resulting release packages?

**Comment by toban** [comment]
> > We could also just remove the streaming-updater-producer when we build here, might be the better solution.
> 
> I didn't fully get this comment. Do you mean the the new version of "WDQS" includes the service ("streaming-updater-producer") packed in, that Wikibase users wouldn't use (for now)? And suggest to remove it from the resulting release packages?

Exactly, not sure if it is as easy as just removing it. But if it is then.

1. We don't have to worry about anyone using that thing (we don't support it AFAIK or has told anyone how to do it)
2. I contains a vulnerable version of log4j that would require a fix if used.

**Comment by manicki** [comment]
> Exactly, not sure if it is as easy as just removing it. But if it is then.
> 
>     1. We don't have to worry about anyone using that thing (we don't support it AFAIK or has told anyone how to do it)
> 
>     2. I contains a vulnerable version of log4j that would require a fix if used.
> 
> 
> `streaming-updater-producer-0.3.96-jar-with-dependencies.jar`is included in the service dist

thanks. Right, it might be tempting, but that said it might lead to WMDE essentially building a custom version of WDQS, which I am not sure is what WMDE should do.
My Java days are are a distant memory now, but looking at [WDQS's pom.xml](https://github.com/wikimedia/wikidata-query-rdf/blob/444ff1b7ba11074f9ec8f07e9a334848ff5ae541/pom.xml#L808) `streaming-updater-producer` is a dependency of the whole thing. And while it does not seem to be needed or used in any of the components we expect people to use, it might still require to rebuild jars that runs without it?

Re log4j issue - if not tempering the pom file, then we might at least ensure the updater if ever used by a curious explorer, the no lookups options would be set by default. But that will probably (?) mean adding it to the example config file, which is not ideal (to reference not used components there). Ideally there would be WDQS version already up which patches the vulnerability but that might still take a bit we wouldn't like to wait.

**Comment by toban** [comment]
> > Exactly, not sure if it is as easy as just removing it. But if it is then.
> > ```
> > 1. We don't have to worry about anyone using that thing (we don't support it AFAIK or has told anyone how to do it)
> > 
> > 2. I contains a vulnerable version of log4j that would require a fix if used.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `streaming-updater-producer-0.3.96-jar-with-dependencies.jar`is included in the service dist
> 
> thanks. Right, it might be tempting, but that said it might lead to WMDE essentially building a custom version of WDQS, which I am not sure is what WMDE should do. My Java days are are a distant memory now, but looking at [WDQS's pom.xml](https://github.com/wikimedia/wikidata-query-rdf/blob/444ff1b7ba11074f9ec8f07e9a334848ff5ae541/pom.xml#L808) `streaming-updater-producer` is a dependency of the whole thing. And while it does not seem to be needed or used in any of the components we expect people to use, it might still require to rebuild jars that runs without it?
> 
> Re log4j issue - if not tempering the pom file, then we might at least ensure the updater if ever used by a curious explorer, the no lookups options would be set by default. But that will probably (?) mean adding it to the example config file, which is not ideal (to reference not used components there). Ideally there would be WDQS version already up which patches the vulnerability but that might still take a bit we wouldn't like to wait.

Yeah ok, lets not tamper with the contents.

**Comment by toban** [comment]
Ok this seems to pass now but lets merge https://github.com/wmde/wikibase-release-pipeline/pull/264 first

**Comment by manicki** [comment]
I'd be eager to approve it once https://github.com/wmde/wikibase-release-pipeline/pull/264 has landed on the main branch,

**Pull request merged**
