### PR TITLE
T346210 test_example action is wasteful

### PR DESCRIPTION
**Pull request by rti**
https://phabricator.wikimedia.org/T346210

### CODE REVIEW

**Review by RickiJay-WMDE — COMMENTED** [review]
Under what circumstances does the action now trigger? How do you manually trigger it?

**Comment by rti** [comment]
> Under what circumstances does the action now trigger? How do you manually trigger it?

It can only get triggered manually now. You can do it via the actions UI on the github website.

screenshot-20230925090056

**Review by RickiJay-WMDE — APPROVED** [review]

**Comment by adeeri** [comment]
> > Under what circumstances does the action now trigger? How do you manually trigger it?
> 
> It can only get triggered manually now. You can do it via the actions UI on the github website.
> 
> screenshot-20230925090056

If not on every run, when would you want to trigger it?

**Comment by rti** [comment]
> If not on every run, when would you want to trigger it?

This is a very good question. I think we still need a process for that. I'd say directly before we publish a release. I think this will naturally come up again when we discuss our distribution story. I added a note here: https://phabricator.wikimedia.org/T340234

**Comment by rti** [comment]
@adeeri Do you agree merging it?

**Comment by adeeri** [comment]
> @adeeri Do you agree merging it?

Yes, thanks for adding the note so we don't lose it!

**Review by adeeri — APPROVED** [review]

**Pull request merged**
