### PR TITLE
fix: injected standard prefixes reference wikidata

### PR DESCRIPTION
**Pull request by rti**
~~As reported in #798, default prefixes injected by WDQS did not align with the `WIKIBASE_CONCEPT_URI` setting added in #771. This PR fixes it.~~

As reported in #798, the "standard prefixes" injected by WDQS do not align with the WIKIBASE_CONCEPT_URI setting introduced in #771, nor do they match the corresponding values for Wikidata. Currently, the WDQS-injected "standard prefixes" (such as `wd:`) reference `http://wikidata/`, which is the internal hostname of the wikibase/mediawiki container within the Docker network.

Particularly in the context of federation, it is essential to maintain the "standard prefixes" for referencing Wikidata [1] [2]. To accommodate the local Wikibase instance, prefixes can be set inline, as is currently done on wikibase.cloud [2]. This pull request addresses this discrepancy and updates the "standard prefixes" to point to Wikidata. Additional context can be found in [3].

[1] https://www.mediawiki.org/wiki/Wikibase/Wikibase.cloud/First_steps#View_your_data_using_the_Query_Service
[2] https://phabricator.wikimedia.org/T335448
[3] https://phabricator.wikimedia.org/T379232

### CODE REVIEW

**Review by darthmon — DISMISSED** [review]
it all looks good to me :)

**Comment by rti** [comment]
Thanks for your thoughts @tarrow, maybe this is not the best idea, even as a temporary solution. Thanks for catching that. Interestingly, the use of wikibaseHost goes back to 2021 to the birth of "example" (78f1acf3).

**Comment by tarrow** [comment]
Yeah, TBH I think there was never a proper specification for how this should all behave.

I also wondered if the `WIKIBASE_HOST_PROPERTY` is important to be set for some other functionality (like the `label` service) or something.

I'd actually question if "magically injecting prefixes" was ever a desirable thing from a product standpoint. It saves a tiny bit of typing or clicking a "add prefixes" button in some UI at the expense of some real mystery for the user. 

I skimmed the SPARQL spec for how acceptable or not it would be to have this magic insertion of prefixes and couldn't find any strong evidence for or against.

**Review by tarrow — COMMENTED** [review]
LGTM but I'm now also hoping that this doesn't impact in some way the "label" SERVICE; I wonder if you already checked this?

**Comment by tarrow** [comment]
I was merely commenting and not requesting changes/approval) because I'd not care to tread on any toes of people not in my team :)

**Review by lorenjohnson — APPROVED** [review]
I haven't fully explored this, but to the 70% that I do grok what is happening here this seems like a clear and needed fix. The comment is appreciated. So this won't break current configuration for folks?

**Comment by rti** [comment]
> LGTM but I'm now also hoping that this doesn't impact in some way the "label" SERVICE; I wonder if you already checked this?

Thanks for catching that. I just double checked and the label service works correctly in e.g.

```sparql
PREFIX PP: <https://wikibase.example/prop/>

SELECT ?aLabel
WHERE
{
  ?a PP:P1 ?c
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE]". }
}
```

**Comment by rti** [comment]
> So this won't break current configuration for folks?

Well, I would say: "it finally works as expected". So, "no", because I would consider this a bug fix.

**Pull request merged**
